"""Ajout de la colonne password_hash à User

Revision ID: 27bf16368b04
Revises: 71553a1081bc
Create Date: 2024-06-27 21:23:34.634259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bf16368b04'
down_revision = '71553a1081bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'menu_item', ['items'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('items')

    op.create_table('order_items',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menuitem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['menuitem_id'], ['menu_item.id'], name='order_items_menuitem_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_items_order_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'menuitem_id', name='order_items_pkey')
    )
    # ### end Alembic commands ###
