"""mise à jour

Revision ID: 71553a1081bc
Revises: dd6a4a63a5af
Create Date: 2024-06-27 20:13:41.624667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71553a1081bc'
down_revision = 'dd6a4a63a5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('items')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.VARCHAR(length=500), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
