"""Migrate

Revision ID: 9d9ba709f44f
Revises: 6f4ad9281ce5
Create Date: 2024-06-14 03:42:40.808668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9ba709f44f'
down_revision = '6f4ad9281ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mot_de_passe_hash', sa.String(length=150), nullable=False))
        batch_op.drop_column('mot_de_passe')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mot_de_passe', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('mot_de_passe_hash')

    # ### end Alembic commands ###
